### ISSUE TITLE
AnalogTapeModel

### ISSUE THREAD

**Issue by fpesari** [geekosdawproject/geekosdaw-issues#40]
**Category**: Standalone (JACK), Plugin (VST)
**Description**: Physical modelling signal processing for analog tape recording
**License**: GPLv3
**Web page or repository**: https://github.com/jatinchowdhury18/AnalogTapeModel

**Comment by KottV** [comment]
it's in my repo https://build.opensuse.org/package/show/home:kill_it:JUCE/CHOWTapeModel
LV2 porting is on way

**Comment by KottV** [comment]
LV2 build crashes with segfault
If someone wants to join fixing - welcome
```
Thread 1 "jalv.gtk" received signal SIGSEGV, Segmentation fault.
HysteresisProcessor::prepareToPlay (this=0x555555c3da48, sampleRate=44100, samplesPerBlock=941) at ../../Source/Processors/Hysteresis/HysteresisProcessor.cpp:81
81          overSamplingFactor = (int) powf(2.0f, *osParam + 1);
(gdb) bt
#0  0x00007fffe7a475c4 in HysteresisProcessor::prepareToPlay(double, int) (this=0x555555c3da48, sampleRate=44100, samplesPerBlock=941) at ../../Source/Processors/Hysteresis/HysteresisProcessor.cpp:81
#1  0x00007fffe79f074f in ChowtapeModelAudioProcessor::prepareToPlay(double, int) (this=0x555555c3d290, sampleRate=44100, samplesPerBlock=941) at ../../Source/PluginProcessor.cpp:120
#2  0x00007fffe75eb9c2 in JuceLv2Wrapper::lv2Activate() (this=0x555555c3cd90) at /usr/share/juce/modules/juce_audio_plugin_client/LV2/juce_LV2_Wrapper.cpp:1343
#3  0x00007fffe75e720c in juceLV2_Activate(LV2_Handle) (handle=0x555555c3cd90) at /usr/share/juce/modules/juce_audio_plugin_client/LV2/juce_LV2_Wrapper.cpp:1985
#4  0x000055555555cdce in lilv_instance_activate ()
#5  0x0000555555561758 in jalv_open ()
#6  0x0000555555561b98 in main ()
(gdb) list
76      }
77
78      void HysteresisProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
79      {
80          fs = (float) sampleRate;
81          overSamplingFactor = (int) powf(2.0f, *osParam + 1);
82
83          for (int ch = 0; ch < 2; ++ch)
84          {
85              drive[ch].skip (numSteps);

```

**Comment by fpesari** [comment]
Done
